# Generated by Django 5.1.1 on 2024-09-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transctions', '0019_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
